[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "asv_bwrap"
author = "Pauli Virtanen"
author-email = "pav@iki.fi"
home-page = "https://github.com/pv/asv-bwrap"
requires = ["lockfile", "qtoml"]

[tool.flit.scripts]
asv-bwrap = "asv_bwrap.main:main"
